# -*- coding: utf-8 -*-
"""geoCoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRxBEob317gQgotBZSRKmA-iWG4KGAu0
"""

!pip install folium geopy

import folium
from geopy.geocoders import Nominatim
from IPython.display import display, HTML

location_name = input("Enter your loacation : ")
geolactor = Nominatim(user_agent="geoapi")
location = geolactor.geocode(location_name)

if location:
    latitude = location.latitude
    longitude = location.longitude

    map_object = folium.Map(location=[latitude, longitude], zoom_start=12)
    marker = folium.Marker([latitude, longitude], popup=location_name)
    marker.add_to(map_object)

    display(HTML(map_object._repr_html_()))
else:
  print("Location not found. Try again !!")

